### ISSUE TITLE
Pitfalls in using clock()

### ISSUE THREAD

**Issue by Sachin-A** [Sachin-A/Blake2b#10]
Depending on your system's implementation, two successive calls to clock() would return the same value, if the CPU time consumed is less than the precision of the clock() function.
Sometimes, keyed hashing/ unkeyed hashing time is returned as 0.000000 because of this.
Try something like
`while ((end = clock()) == start) {
        count ++;
 }`
to figure out what the clock() function's precision is on your system, _although we probably shouldn't be relying on that_

**Comment by franziskuskiefer** [comment]
I think for a basic test it's fine to use clock. In NSS you can use PR_Now for that [1].
For more accurate timings you should use clock cycles.

[1] https://searchfox.org/mozilla-central/source/nsprpub/pr/src/md/unix/unix.c#3005

**Comment by Sachin-A** [comment]
Ah that's good so we'll let that be and handle it at integration.
I'll close this issue then if that's fine with Venkkatesh.
